from selenium.webdriver.common.by import By


class CovidFinLocators:
    dob = (By.CSS_SELECTOR, "input[data-name=\"content.policyHolder.dob\"]")
    is_insured = (By.CSS_SELECTOR, "label[for=\"content.insuredPerson.is.type_custom_input\"]")
    male = (By.ID, "content.policyHolder.sex-male")
    insured_dob = (By.CSS_SELECTOR, "input[data-name=\"content.insuredPerson.dob\"]")
    insured_male = (By.ID, "content.insuredPerson.sex-male")
    button1 = (By.CSS_SELECTOR, "table tr:last-child>td:nth-child(2)>button")
    insurer_lastname = (By.NAME, "content.policyHolder.lastName")
    insurer_firstname = (By.NAME, "content.policyHolder.firstName")
    insurer_middlename = (By.NAME, "content.policyHolder.middleName")
    insurer_phone = (By.NAME, "content.policyHolder.phone")
    insurer_email = (By.NAME,"content.policyHolder.email")
    insurer_email2 = (By.NAME, "content.policyHolder.email2")
    insurer_seria = (By.NAME, "content.policyHolder.document.seria")
    insurer_number = (By.NAME, "content.policyHolder.document.number")
    continue_button = (By.CSS_SELECTOR, "div.text-right>button")
    insured_lastname = (By.NAME, "content.insuredPerson.lastName")
    insured_firstname = (By.NAME, "content.insuredPerson.firstName")
    insured_middlename = (By.NAME, "content.insuredPerson.middleName")
    insured_phone = (By.NAME, "content.insuredPerson.phone")
    insured_email = (By.NAME, "content.insuredPerson.email")
    insured_email2 = (By.NAME, "content.insuredPerson.email2")
    insured_document_type = (By.ID, "react-select-2-input")
    insured_seria = (By.NAME, "content.insuredPerson.document.seria")
    insured_number = (By.NAME, "content.insuredPerson.document.number")
    Accept_All_Input = (By.CSS_SELECTOR, "label[for=\"content.temp.acceptAll_custom_input\"")
