chromedriver_path = r"D:\KIRILL\Utilities\chromedriver.exe"
chrome_binary_path = r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
geckodriver_path = r"D:\KIRILL\Utilities\geckodriver.exe"
firefox_binary_path = r"C:\Program Files\Mozilla Firefox\firefox.exe"
iedriver_path = r"D:\KIRILL\Utilities\IEDriverServer.exe"
operadriver_path = r"D:\KIRILL\Utilities\operadriver.exe"